package handler

import (
	"errors"
	"net/http"
	"strconv"

	"github.com/so77id/nalanda/apps/server/internal/app/web/flash"
	"github.com/so77id/nalanda/apps/server/internal/app/web/middleware"
	"github.com/so77id/nalanda/apps/server/internal/app/web/view"
	"github.com/so77id/nalanda/apps/server/internal/domain/jobs"
	"github.com/so77id/nalanda/apps/server/internal/domain/survey"
)

// The run screens of a survey (issue #310): create one (screen 8), and —
// from S6 — its dashboard (screen 9). The run's PDF is generated by the
// `survey_generate` job on the one runner (ADR-0079); nothing here calls
// the worker.

// Run routes. A run is addressed under its survey, {id}, as every survey
// route is, and by its own {rid}.
const (
	SurveyRunsPath   = "/surveys/{id}/runs"
	SurveyRunNewPath = "/surveys/{id}/runs/new"
)

// SurveyRunsPathFor builds the URL a new run is POSTed to.
func SurveyRunsPathFor(id int64) string { return SurveyPathFor(id) + "/runs" }

// SurveyRunNewPathFor builds the URL of the new-run form.
func SurveyRunNewPathFor(id int64) string { return SurveyRunsPathFor(id) + "/new" }

// defaultRunCopies is the form's starting value: a class plus a margin.
const defaultRunCopies = 45

// NewRun renders the empty run form (screen 8).
func (h *Surveys) NewRun(w http.ResponseWriter, r *http.Request) {
	one, ok := h.survey(w, r)
	if !ok {
		return
	}
	h.renderRunForm(w, r, one, http.StatusOK,
		view.RunFormValues{AppliedOn: h.today(), Copies: strconv.Itoa(defaultRunCopies)}, nil, "")
}

// CreateRun creates the run (the sync half: row, snapshot, source) and
// queues its sheet's generation.
func (h *Surveys) CreateRun(w http.ResponseWriter, r *http.Request) {
	one, ok := h.survey(w, r)
	if !ok {
		return
	}
	if err := r.ParseForm(); err != nil {
		h.renderRunForm(w, r, one, http.StatusUnprocessableEntity, view.RunFormValues{}, nil,
			"No se pudo leer el formulario. Vuelve a intentarlo.")
		return
	}
	values := view.RunFormValues{
		Name: r.PostFormValue("name"), AppliedOn: r.PostFormValue("applied_on"), Copies: r.PostFormValue("copies"),
	}
	copies, err := strconv.Atoi(values.Copies)
	if err != nil {
		h.renderRunForm(w, r, one, http.StatusUnprocessableEntity, values,
			map[string]string{survey.FieldCopies: "Escribe un número de copias."}, "")
		return
	}
	professor, ok := middleware.ProfessorFrom(r.Context())
	if !ok {
		middleware.WriteError(w, r, http.StatusForbidden, "Necesitas iniciar sesión.")
		return
	}

	run, err := h.Service.CreateRun(r.Context(), one.ID, professor.ID,
		survey.RunDraft{Name: values.Name, AppliedOn: values.AppliedOn, Copies: copies})
	switch {
	case errors.Is(err, survey.ErrInvalid):
		h.renderRunForm(w, r, one, http.StatusUnprocessableEntity, values, surveyFieldErrors(err), "")
		return
	case errors.Is(err, survey.ErrEmptyBank):
		flash.Set(w, h.secureCookie, "Agrega al menos una pregunta antes de crear una pasada.")
		http.Redirect(w, r, SurveyPathFor(one.ID), http.StatusSeeOther)
		return
	case errors.Is(err, survey.ErrSurveyNotFound):
		middleware.WriteError(w, r, http.StatusNotFound, "Esa encuesta no existe.")
		return
	case err != nil:
		h.Log.Error("creating a survey run", "survey", one.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
		return
	}

	if _, err := h.Runner.Submit(r.Context(), strconv.FormatInt(run.ID, 10), jobs.KindSurveyGenerate,
		survey.EncodeRunPayload(one.ID)); err != nil {
		// The run and its source exist; only the queueing failed. Say so
		// rather than pretend the PDF is on its way.
		h.Log.Error("queueing a run's sheet", "survey", one.ID, "run", run.ID, "error", err)
		flash.Set(w, h.secureCookie, "Pasada creada, pero no se pudo encolar la generación del PDF. "+
			"Vuelve a intentarlo en unos minutos.")
		http.Redirect(w, r, h.runLanding(one.ID, run.ID), http.StatusSeeOther)
		return
	}
	flash.Set(w, h.secureCookie, "Pasada #"+strconv.Itoa(run.Number)+" creada. El PDF se está generando.")
	http.Redirect(w, r, h.runLanding(one.ID, run.ID), http.StatusSeeOther)
}

// runLanding is where creating a run lands: the survey page's runs card.
func (h *Surveys) runLanding(surveyID, _ int64) string {
	return SurveyPathFor(surveyID) + "#pasadas"
}

func (h *Surveys) renderRunForm(w http.ResponseWriter, r *http.Request, one survey.Survey, status int,
	values view.RunFormValues, errs map[string]string, notice string) {
	questions, err := h.Service.Questions(r.Context(), one.ID)
	if err != nil {
		h.Log.Warn("reading the bank for the run form", "survey", one.ID, "error", err)
	}
	page := view.SurveyRunFormPage{
		Page:          middleware.PageFor(r, "Nueva pasada"),
		SurveyName:    one.Name,
		Heading:       "Nueva pasada · " + one.Name,
		Action:        SurveyRunsPathFor(one.ID),
		Submit:        "Crear pasada y generar PDF",
		CancelURL:     SurveyPathFor(one.ID),
		ShowCopies:    true,
		QuestionCount: len(questions),
		Values:        values,
		Errors:        errs,
		Notice:        notice,
	}
	if err := view.RenderSurveyRunForm(w, status, page); err != nil {
		h.Log.Error("rendering the run form", "survey", one.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
	}
}

// today is the form's default date, from the service clock.
func (h *Surveys) today() string {
	return h.Service.Now().Format("2006-01-02")
}
