package handler

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/so77id/nalanda/apps/server/internal/app/web/flash"
	"github.com/so77id/nalanda/apps/server/internal/app/web/middleware"
	"github.com/so77id/nalanda/apps/server/internal/app/web/view"
	"github.com/so77id/nalanda/apps/server/internal/domain/jobs"
	"github.com/so77id/nalanda/apps/server/internal/domain/survey"
)

// The run screens of a survey (issue #310): create one (screen 8), and —
// from S6 — its dashboard (screen 9). The run's PDF is generated by the
// `survey_generate` job on the one runner (ADR-0079); nothing here calls
// the worker.

// Run routes. A run is addressed under its survey, {id}, as every survey
// route is, and by its own {rid}.
const (
	SurveyRunsPath   = "/surveys/{id}/runs"
	SurveyRunNewPath = "/surveys/{id}/runs/new"
)

// SurveyRunsPathFor builds the URL a new run is POSTed to.
func SurveyRunsPathFor(id int64) string { return SurveyPathFor(id) + "/runs" }

// SurveyRunNewPathFor builds the URL of the new-run form.
func SurveyRunNewPathFor(id int64) string { return SurveyRunsPathFor(id) + "/new" }

// defaultRunCopies is the form's starting value: a class plus a margin.
const defaultRunCopies = 45

// NewRun renders the empty run form (screen 8).
func (h *Surveys) NewRun(w http.ResponseWriter, r *http.Request) {
	one, ok := h.survey(w, r)
	if !ok {
		return
	}
	h.renderRunForm(w, r, one, http.StatusOK,
		view.RunFormValues{AppliedOn: h.today(), Copies: strconv.Itoa(defaultRunCopies)}, nil, "")
}

// CreateRun creates the run (the sync half: row, snapshot, source) and
// queues its sheet's generation.
func (h *Surveys) CreateRun(w http.ResponseWriter, r *http.Request) {
	one, ok := h.survey(w, r)
	if !ok {
		return
	}
	if err := r.ParseForm(); err != nil {
		h.renderRunForm(w, r, one, http.StatusUnprocessableEntity, view.RunFormValues{}, nil,
			"No se pudo leer el formulario. Vuelve a intentarlo.")
		return
	}
	values := view.RunFormValues{
		Name: r.PostFormValue("name"), AppliedOn: r.PostFormValue("applied_on"), Copies: r.PostFormValue("copies"),
	}
	copies, err := strconv.Atoi(values.Copies)
	if err != nil {
		h.renderRunForm(w, r, one, http.StatusUnprocessableEntity, values,
			map[string]string{survey.FieldCopies: "Escribe un número de copias."}, "")
		return
	}
	professor, ok := middleware.ProfessorFrom(r.Context())
	if !ok {
		middleware.WriteError(w, r, http.StatusForbidden, "Necesitas iniciar sesión.")
		return
	}

	run, err := h.Service.CreateRun(r.Context(), one.ID, professor.ID,
		survey.RunDraft{Name: values.Name, AppliedOn: values.AppliedOn, Copies: copies})
	switch {
	case errors.Is(err, survey.ErrInvalid):
		h.renderRunForm(w, r, one, http.StatusUnprocessableEntity, values, surveyFieldErrors(err), "")
		return
	case errors.Is(err, survey.ErrEmptyBank):
		flash.Set(w, h.secureCookie, "Agrega al menos una pregunta antes de crear una pasada.")
		http.Redirect(w, r, SurveyPathFor(one.ID), http.StatusSeeOther)
		return
	case errors.Is(err, survey.ErrSurveyNotFound):
		middleware.WriteError(w, r, http.StatusNotFound, "Esa encuesta no existe.")
		return
	case err != nil:
		h.Log.Error("creating a survey run", "survey", one.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
		return
	}

	if _, err := h.Runner.Submit(r.Context(), strconv.FormatInt(run.ID, 10), jobs.KindSurveyGenerate,
		survey.EncodeRunPayload(one.ID)); err != nil {
		// The run and its source exist; only the queueing failed. Say so
		// rather than pretend the PDF is on its way.
		h.Log.Error("queueing a run's sheet", "survey", one.ID, "run", run.ID, "error", err)
		flash.Set(w, h.secureCookie, "Pasada creada, pero no se pudo encolar la generación del PDF. "+
			"Vuelve a intentarlo en unos minutos.")
		http.Redirect(w, r, SurveyRunPathFor(one.ID, run.ID), http.StatusSeeOther)
		return
	}
	flash.Set(w, h.secureCookie, "Pasada #"+strconv.Itoa(run.Number)+" creada. El PDF se está generando.")
	// Its dashboard, where the banner shows the PDF being generated.
	http.Redirect(w, r, SurveyRunPathFor(one.ID, run.ID), http.StatusSeeOther)
}

func (h *Surveys) renderRunForm(w http.ResponseWriter, r *http.Request, one survey.Survey, status int,
	values view.RunFormValues, errs map[string]string, notice string) {
	questions, err := h.Service.Questions(r.Context(), one.ID)
	if err != nil {
		h.Log.Warn("reading the bank for the run form", "survey", one.ID, "error", err)
	}
	page := view.SurveyRunFormPage{
		Page:          middleware.PageFor(r, "Nueva pasada"),
		SurveyName:    one.Name,
		Heading:       "Nueva pasada · " + one.Name,
		Action:        SurveyRunsPathFor(one.ID),
		Submit:        "Crear pasada y generar PDF",
		CancelURL:     SurveyPathFor(one.ID),
		ShowCopies:    true,
		QuestionCount: len(questions),
		Values:        values,
		Errors:        errs,
		Notice:        notice,
	}
	if err := view.RenderSurveyRunForm(w, status, page); err != nil {
		h.Log.Error("rendering the run form", "survey", one.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
	}
}

// today is the form's default date, from the service clock.
func (h *Surveys) today() string {
	return h.Service.Now().Format(time.DateOnly)
}

// The run's own routes (issue #310 S6, screen 9).
const (
	SurveyRunPath       = "/surveys/{id}/runs/{rid}"
	SurveyRunEditPath   = "/surveys/{id}/runs/{rid}/edit"
	SurveyRunCancelPath = "/surveys/{id}/runs/{rid}/cancel"
	SurveyRunSheetPath  = "/surveys/{id}/runs/{rid}/sujet.pdf"
)

// SurveyRunPathFor builds the URL of a run's dashboard.
func SurveyRunPathFor(surveyID, runID int64) string {
	return SurveyRunsPathFor(surveyID) + "/" + strconv.FormatInt(runID, 10)
}

// SurveyRunEditPathFor builds the URL of a run's edit form.
func SurveyRunEditPathFor(surveyID, runID int64) string {
	return SurveyRunPathFor(surveyID, runID) + "/edit"
}

// SurveyRunCancelPathFor builds the URL that cancels a run.
func SurveyRunCancelPathFor(surveyID, runID int64) string {
	return SurveyRunPathFor(surveyID, runID) + "/cancel"
}

// SurveyRunSheetPathFor builds the URL of a run's printable PDF.
func SurveyRunSheetPathFor(surveyID, runID int64) string {
	return SurveyRunPathFor(surveyID, runID) + "/sujet.pdf"
}

// RunDetail renders one run (screen 9): its banner, its steps, its counts
// and the actions its state allows.
func (h *Surveys) RunDetail(w http.ResponseWriter, r *http.Request) {
	one, run, ok := h.surveyRun(w, r)
	if !ok {
		return
	}
	snapshot, err := h.Service.RunQuestions(r.Context(), run.ID)
	if err != nil {
		h.Log.Error("reading a run's snapshot", "run", run.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
		return
	}
	pdfReady, pdfStatus := h.sheetState(r.Context(), run)
	latest := h.latestRunJob(r.Context(), run)

	title := "Pasada #" + strconv.Itoa(run.Number)
	if run.Name != "" {
		title += " · " + run.Name
	}
	page := view.SurveyRunPage{
		Page:          middleware.PageFor(r, title),
		SurveyName:    one.Name,
		SurveyURL:     SurveyPathFor(one.ID),
		Title:         title,
		AppliedOn:     run.AppliedOn,
		Copies:        run.Copies,
		QuestionCount: len(snapshot),
		Cancelled:     run.State == survey.RunCancelled,
		StateLabel:    runStateLabel(run.State),
		Banner:        runBanner(latest),
		PDFReady:      pdfReady,
		PDFURL:        SurveyRunSheetPathFor(one.ID, run.ID),
		ReadLabel:     "—",
		ReviewLabel:   "—",
	}
	if run.State == survey.RunOpen {
		page.EditURL = SurveyRunEditPathFor(one.ID, run.ID)
		page.CanCancel = !inFlight(latest)
		page.CancelAction = SurveyRunCancelPathFor(one.ID, run.ID)
	}
	page.Steps = []view.RunStep{
		{Label: "PDF", Status: pdfStatus, Done: pdfReady},
		{Label: "Escaneos", Status: "pendiente"},
		{Label: "Revisión", Status: "pendiente"},
		{Label: "Cerrada", Status: "pendiente"},
	}
	page.Flash = flash.Consume(w, r, h.secureCookie)

	if err := view.RenderSurveyRun(w, page); err != nil {
		h.Log.Error("rendering a run", "run", run.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
	}
}

// RunSheet serves a run's printable PDF once its generation is done.
func (h *Surveys) RunSheet(w http.ResponseWriter, r *http.Request) {
	_, run, ok := h.surveyRun(w, r)
	if !ok {
		return
	}
	if run.State == survey.RunCancelled {
		middleware.WriteError(w, r, http.StatusNotFound, "Esta pasada se canceló: su PDF ya no se imprime.")
		return
	}
	if ready, _ := h.sheetState(r.Context(), run); !ready {
		middleware.WriteError(w, r, http.StatusNotFound, "El PDF de esta pasada todavía no está listo.")
		return
	}
	f, err := os.Open(h.Service.SheetPath(run))
	if err != nil {
		h.Log.Error("opening a run's sheet", "run", run.ID, "error", err)
		middleware.WriteError(w, r, http.StatusNotFound, "No se encontró el PDF de esta pasada.")
		return
	}
	defer func() { _ = f.Close() }()
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition",
		fmt.Sprintf(`attachment; filename="encuesta-%d-pasada-%d.pdf"`, run.SurveyID, run.Number))
	if _, err := io.Copy(w, f); err != nil {
		h.Log.Warn("streaming a run's sheet", "run", run.ID, "error", err)
	}
}

// EditRun renders a run's name/date form; the copies are printed.
func (h *Surveys) EditRun(w http.ResponseWriter, r *http.Request) {
	one, run, ok := h.surveyRun(w, r)
	if !ok {
		return
	}
	h.renderRunEditForm(w, r, one, run, http.StatusOK,
		view.RunFormValues{Name: run.Name, AppliedOn: run.AppliedOn}, nil)
}

// UpdateRun rewrites a run's name and date.
func (h *Surveys) UpdateRun(w http.ResponseWriter, r *http.Request) {
	one, run, ok := h.surveyRun(w, r)
	if !ok {
		return
	}
	if err := r.ParseForm(); err != nil {
		h.renderRunEditForm(w, r, one, run, http.StatusUnprocessableEntity, view.RunFormValues{},
			map[string]string{survey.FieldAppliedOn: "No se pudo leer el formulario. Vuelve a intentarlo."})
		return
	}
	values := view.RunFormValues{Name: r.PostFormValue("name"), AppliedOn: r.PostFormValue("applied_on")}
	err := h.Service.UpdateRun(r.Context(), one.ID, run.ID, survey.RunDraft{Name: values.Name, AppliedOn: values.AppliedOn})
	switch {
	case errors.Is(err, survey.ErrInvalid):
		h.renderRunEditForm(w, r, one, run, http.StatusUnprocessableEntity, values, surveyFieldErrors(err))
		return
	case errors.Is(err, survey.ErrRunNotOpen):
		flash.Set(w, h.secureCookie, "Esta pasada ya no está abierta: no se puede editar.")
		http.Redirect(w, r, SurveyRunPathFor(one.ID, run.ID), http.StatusSeeOther)
		return
	case errors.Is(err, survey.ErrRunNotFound):
		middleware.WriteError(w, r, http.StatusNotFound, "Esa pasada no existe.")
		return
	case err != nil:
		h.Log.Error("updating a run", "run", run.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
		return
	}
	flash.Set(w, h.secureCookie, "Pasada actualizada.")
	http.Redirect(w, r, SurveyRunPathFor(one.ID, run.ID), http.StatusSeeOther)
}

// CancelRun cancels an open run with no job in flight. A refusal is a
// flash on the run's page (backend-code-style.md §Flash), never a 4xx.
func (h *Surveys) CancelRun(w http.ResponseWriter, r *http.Request) {
	one, run, ok := h.surveyRun(w, r)
	if !ok {
		return
	}
	back := SurveyRunPathFor(one.ID, run.ID)
	// A job about the run is still running: cancelling under it is the
	// race add-a-backend-endpoint.md's fourth synchronous rule forbids. A
	// failed read answers "not in flight" — cancelling destroys nothing
	// the runner could not tolerate (GenerateRunSheet refuses a run that
	// is no longer open).
	if inFlight(h.latestRunJob(r.Context(), run)) {
		flash.Set(w, h.secureCookie, "El PDF de esta pasada se está generando. Espera a que termine y vuelve a intentarlo.")
		http.Redirect(w, r, back, http.StatusSeeOther)
		return
	}
	err := h.Service.CancelRun(r.Context(), one.ID, run.ID)
	switch {
	case errors.Is(err, survey.ErrRunNotCancellable):
		flash.Set(w, h.secureCookie, "Esta pasada ya no se puede cancelar.")
		http.Redirect(w, r, back, http.StatusSeeOther)
		return
	case errors.Is(err, survey.ErrRunNotFound):
		middleware.WriteError(w, r, http.StatusNotFound, "Esa pasada no existe.")
		return
	case err != nil:
		h.Log.Error("cancelling a run", "run", run.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
		return
	}
	flash.Set(w, h.secureCookie, "Pasada #"+strconv.Itoa(run.Number)+" cancelada.")
	http.Redirect(w, r, SurveyPathFor(one.ID)+"#pasadas", http.StatusSeeOther)
}

func (h *Surveys) renderRunEditForm(w http.ResponseWriter, r *http.Request, one survey.Survey, run survey.Run,
	status int, values view.RunFormValues, errs map[string]string) {
	page := view.SurveyRunFormPage{
		Page:       middleware.PageFor(r, "Editar pasada"),
		SurveyName: one.Name,
		Heading:    "Editar pasada #" + strconv.Itoa(run.Number),
		Action:     SurveyRunEditPathFor(one.ID, run.ID),
		Submit:     "Guardar",
		CancelURL:  SurveyRunPathFor(one.ID, run.ID),
		Values:     values,
		Errors:     errs,
	}
	if err := view.RenderSurveyRunForm(w, status, page); err != nil {
		h.Log.Error("rendering the run edit form", "run", run.ID, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
	}
}

// surveyRun reads the {id} survey and its {rid} run, answering 404 itself
// when either is absent — including a run of ANOTHER survey.
func (h *Surveys) surveyRun(w http.ResponseWriter, r *http.Request) (survey.Survey, survey.Run, bool) {
	one, ok := h.survey(w, r)
	if !ok {
		return survey.Survey{}, survey.Run{}, false
	}
	rid, err := strconv.ParseInt(r.PathValue("rid"), 10, 64)
	if err != nil || rid <= 0 {
		middleware.WriteError(w, r, http.StatusNotFound, "Esa pasada no existe.")
		return survey.Survey{}, survey.Run{}, false
	}
	run, err := h.Service.Run(r.Context(), one.ID, rid)
	switch {
	case errors.Is(err, survey.ErrRunNotFound):
		middleware.WriteError(w, r, http.StatusNotFound, "Esa pasada no existe.")
		return survey.Survey{}, survey.Run{}, false
	case err != nil:
		h.Log.Error("reading a run", "survey", one.ID, "run", rid, "error", err)
		middleware.WriteError(w, r, http.StatusInternalServerError, surveyBroke)
		return survey.Survey{}, survey.Run{}, false
	}
	return one, run, true
}

// sheetState is the PDF step of a run, from its latest generation (#310
// review, COR-4): done is the only ready state; a failed or never-queued
// generation says so instead of reading "en curso" for ever.
func (h *Surveys) sheetState(ctx context.Context, run survey.Run) (ready bool, label string) {
	job, err := h.Jobs.LatestByKind(ctx, strconv.FormatInt(run.ID, 10), jobs.KindSurveyGenerate)
	switch {
	case errors.Is(err, jobs.ErrJobNotFound):
		return false, "no encolado"
	case err != nil:
		h.Log.Warn("reading a run's generation", "run", run.ID, "error", err)
		return false, "desconocido"
	case job.Status == jobs.StatusDone:
		return true, "listo"
	case job.Status == jobs.StatusFailed:
		return false, "falló"
	}
	return false, "en curso"
}

// latestRunJob is the most recent job about the run, or nil when it has
// none or the read failed — a failed read is logged and treated as "no
// job", the banner being an aid and the cancel gate failing open (see
// CancelRun).
func (h *Surveys) latestRunJob(ctx context.Context, run survey.Run) *jobs.Job {
	job, err := h.Jobs.LatestForSubject(ctx, jobs.SubjectSurveyRun, strconv.FormatInt(run.ID, 10))
	if err != nil {
		if !errors.Is(err, jobs.ErrJobNotFound) {
			h.Log.Warn("jobs: reading a run's latest job", "run", run.ID, "error", err)
		}
		return nil
	}
	return &job
}

// inFlight reports whether a job is queued or running.
func inFlight(job *jobs.Job) bool { return job != nil && !job.Status.IsTerminal() }

// runBanner is the run page's banner from the run's latest job — the
// shared bannerFromJob, with the survey's label. A failed job's Detail is
// debug and never shown: every survey Kind writes the worker's English
// there.
func runBanner(job *jobs.Job) *view.JobBanner {
	if job == nil {
		return nil
	}
	return bannerFromJob(*job, surveyJobLabel(job.Kind))
}

// surveyJobLabel names a survey job on its banner.
func surveyJobLabel(k jobs.Kind) string {
	if k == jobs.KindSurveyGenerate {
		return "generación del PDF"
	}
	// Never the raw English kind on a Spanish page.
	return "trabajo de la pasada"
}

// runStateLabel is a run's state as the professor reads it.
func runStateLabel(s survey.RunState) string {
	switch s {
	case survey.RunOpen:
		return "abierta"
	case survey.RunClosed:
		return "cerrada"
	case survey.RunCancelled:
		return "cancelada"
	}
	return string(s)
}
